{"uuid": "49231436-155a-4ec7-be28-cea4bd45ebe7", "children": ["2f6c89de-8963-4e3d-9bc2-cdd3711eea2c", "212dff02-4095-4c7b-8429-2c5af42f8667", "68734dd0-a9e7-460b-a036-a2a88f152126"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Misconfigured -- Invalid type received for 'platformVersion', got '10.0' of type '<type 'float'>' but Sauce OnDemand expects 'string'.\n\nThe following desired capabilities were received:\n{'appium:app': 'storage:filename=Android_Demo_App.apk',\n 'appium:automationName': 'UiAutomator2',\n 'appium:deviceName': 'Google Pixel 3a XL GoogleAPI Emulator',\n 'appium:platformVersion': 10.0,\n 'platformName': 'Android',\n 'sauce:options': {'appiumVersion': '1.17.1',\n                   'build': 'v1.1',\n                   'name': 'appium android test framework'}}\n\n", "trace": "  File \"C:\\Users\\pradn\\PycharmProjects\\pythonselenium\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\pradn\\PycharmProjects\\pythonselenium\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\pradn\\PycharmProjects\\pythonselenium\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 900, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\pradn\\PycharmProjects\\appiumpython\\AppiumFrameworkcloud\\tests\\conftest.py\", line 12, in beforeClass\n    driver=driver1.getcloudDriver(dc.platformVersion,dc.pName)\n  File \"C:\\Users\\pradn\\PycharmProjects\\appiumpython\\AppiumFrameworkcloud\\base\\DriverClass.py\", line 35, in getcloudDriver\n    driver = webdriver.Remote(url, caps, keep_alive=True)\n  File \"C:\\Users\\pradn\\PycharmProjects\\pythonselenium\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 230, in __init__\n    super().__init__(\n  File \"C:\\Users\\pradn\\PycharmProjects\\pythonselenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 288, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\pradn\\PycharmProjects\\pythonselenium\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 320, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"C:\\Users\\pradn\\PycharmProjects\\pythonselenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\pradn\\PycharmProjects\\pythonselenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 213, in check_response\n    raise exception_class(value)\n"}, "start": 1673398561282, "stop": 1673398561478}], "start": 1673398561282, "stop": 1673398561676}